# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipeA' do
pod 'Alamofire', '~> 5.4'



  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecipeA

  target 'RecipeATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RecipeAUITests' do
    # Pods for testing
  end

end
